name: lica_web
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  audioplayers: ^6.1.0
  avatar_glow: ^3.0.1
  cached_network_image: ^3.4.0
  calendar_view: ^1.2.0
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.2.1
  file_picker: ^8.0.7
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_storage: ^12.1.3
  fl_chart: ^0.68.0
  flowery_tts: ^1.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_native_splash: ^2.4.1
  flutter_quill: ^10.2.1
  gauge_indicator: ^0.4.3
  go_router: ^14.2.3
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.6
  google_sign_in: ^6.2.1
  http: ^1.2.2
  icons_launcher: ^3.0.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  photo_view: ^0.15.0
  posthog_flutter: ^4.5.0
  screenshot: ^3.0.0
  syncfusion_flutter_pdfviewer: ^26.2.9
  table_calendar: ^3.1.2
  url_launcher: ^6.3.0
  uuid: ^4.4.2
  youtube_player_iframe: ^5.1.3

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    # Images
    - assets/img/splash/
    - assets/img/side_bar/
    - assets/img/common/
    - assets/img/calendar/
    - assets/img/home/
    - assets/img/chats/
    - assets/img/notes/
    - assets/img/note_box/
    - assets/img/profile/
    - assets/img/dynamic_cv/
    - assets/img/ui_test/
    - assets/img/logo/
    - assets/img/sign_in/
    - assets/img/notepad/
    - assets/img/class_box/
    - assets/img/onboard/
    - assets/img/todos/
    - assets/img/cta/
    # Animation
  # fonts:
  #   - family: "Apple Color Emoji"
  #     fonts:
  #       - asset: assets/fonts/apple_color_emoji.ttf
flutter_native_splash:
  background_image_web: assets/img/splash/background.png
  branding_web: assets/img/splash/branding.png
  image_web: assets/img/splash/image.png
  ios: false
  android: false

icons_launcher:
  image_path: "assets/img/splash/icon.png"
  platforms:
    web:
      enable: true
    android:
      enable: false
    ios:
      enable: false
